version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: translation
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  jtask:
    container_name: jtask
    build:
      dockerfile: Dockerfile
    environment:
      - DB_URL=db
      - POSTGRES_DB=translation
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  pgdata: