version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  jtask:
    container_name: jtask
    build:
      dockerfile: Dockerfile
    environment:
      - DB_URL=db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - API_KEY=${API_KEY}
      - API_URL=${API_URL}
      - API_FOLDER_ID=${API_FOLDER_ID}
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  pgdata: